# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Sagar Mattoo'
tagline:          'Learnings from experience'
description:      'Sagar''s technical blog'
url:              'https://smattoo.github.io'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/

# Author Details
author:         'Sagar Mattoo'
linkedin:       'http://in.linkedin.com/pub/sagar-mattoo/56/7a/18a'
twitter:        'https://twitter.com/mattoosagar'
facebook:       'https://www.facebook.com/sagar.mattoo.77'
gplus:          'https://plus.google.com/106795982492993354177/'

# Google Analytics
gahandler: 'UA-60858224-1'

#if footer-links-visible is 'true' the svg-icons will be shown top on the copy right. 
#else the svg icons will not exist
footersvg: 'true'

footer-links:
  dribbble: 
  email: None
  facebook: 
  flickr: 
  github: 
  instagram: 
  linkedin: 
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  google: None
  twitter: None
  stackoverflow: #users/4388898/peter-zhu # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Disqus
disqushandler: 'sagarmattoo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.7.10
